runtime: java11
entrypoint: java -jar launcher.jar

instance_class: B1

manual_scaling:
  instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
